### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by Segmentational** [maxtheaxe/discount-money-bot#2]
Upon downloading google chrome, given it was a new installation, my PayPal login was never cached; consequently, the program would error out given `Error: Page didn't load in a reasonable amount of time; try again.`

However, Google Chrome did successfully open up and prompt for a PayPal login. Will attempt again after logging in.

**Comment by Segmentational** [comment]
Still shutdown too early and apparently cacheing the login information does not work. The program also grabs handle of Google Chrome and kills the process before I am able to actually sign in. I suggest increasing time for which a user is able to take control of the browser before sigkil itself.

**Comment by Segmentational** [comment]
Another possibility is to use the PayPal API for Venmo/Paypal interfacing rather than depending upon the User's web browser: https://developer.paypal.com/docs/api/overview/

**Comment by maxtheaxe** [comment]
It is intended that the user type in their own login details twice. I have no desire to interact with the details of or take on the responsibility of entering peoples' PayPal login info (though by doing so, it could function more smoothly), because I want to reassure people (including those that can't necessarily understand my code) that I'm not doing anything sketchy without their knowledge.
