### ISSUE TITLE
Web-Browser Stay-Alive Time Duration

### ISSUE THREAD

**Issue by Segmentational** [maxtheaxe/discount-money-bot#4]
*Please see Discord for related video attachment*

https://discord.com/channels/@me/691082204075261982/794643015820902410

**Comment by maxtheaxe** [comment]
Okay, so some sort of exception is obviously happening there, but because I got lazy and just caught all exceptions, instead of `NoSuchElementException` (which is weird, because in other cases nearly identical to this one, I did it properly), I can't be sure that it's actually not finding the Accept Cookies button, which I use as an indicator of page load.

Try it again with the update I just pushed, which only catches `NoSuchElementException`.

**Comment by maxtheaxe** [comment]
Issue was fixed, ended up being in some code added client-side (wasn't pushed), though it brought the problem I detailed above (in my response) to my attention.
